import { readFileSync } from 'node:fs';

import { describe, expect, it } from 'vitest';

import { PACKAGE_FILES, validatePackageFiles } from '../scripts/package-files.mjs';

// The benchmark surface lives behind the default-off `bench` cargo feature, so
// no artifact built by `pnpm run build` may carry it. These committed glue
// files are regenerated by `build:wasm`, which makes an accidental
// feature-enabled build visible as a failing test rather than as shipped bytes.
const GATED_EXPORTS = ['bench_codecs', 'bench_multi_view', 'codec_conformance'];
const SHIPPED_GLUE = [
  'src/wasm/render_wasm.js',
  'src/wasm/render_wasm.d.ts',
  'src/wasm/render_wasm_bg.wasm.d.ts',
  'docs-site/public/demo/render_wasm.js',
  'docs-site/public/demo/render_wasm.d.ts',
];

describe('npm package file contract', () => {
  it('accepts exactly the public package files', () => {
    expect(validatePackageFiles([...PACKAGE_FILES].reverse())).toEqual(PACKAGE_FILES);
  });

  it('rejects missing, extra, and source files', () => {
    expect(() => validatePackageFiles(PACKAGE_FILES.slice(1))).toThrow('missing=[');
    expect(() => validatePackageFiles([...PACKAGE_FILES, 'dist/accidental.txt'])).toThrow('extra=[');
    expect(() => validatePackageFiles([...PACKAGE_FILES, 'rust/src/lib.rs'])).toThrow(
      'forbidden=[rust/src/lib.rs]',
    );
  });
});

describe('shipped wasm surface', () => {
  it.each(SHIPPED_GLUE)('leaves the bench surface out of %s', (file) => {
    const glue = readFileSync(new URL(`../${file}`, import.meta.url), 'utf8');
    for (const symbol of GATED_EXPORTS) expect(glue).not.toContain(symbol);
  });
});
