// @ts-nocheck
import { browser } from 'fumadocs-mdx/runtime/browser';
import type * as Config from '../source.config';

const create = browser<typeof Config, import("fumadocs-mdx/runtime/types").InternalTypeConfig & {
  DocData: {
  }
}>();
const browserCollections = {
  docs: create.doc("docs", {"index.mdx": () => import("../content/docs/index.mdx?collection=docs"), "concepts/camera-model.mdx": () => import("../content/docs/concepts/camera-model.mdx?collection=docs"), "concepts/determinism.mdx": () => import("../content/docs/concepts/determinism.mdx?collection=docs"), "concepts/material-model.mdx": () => import("../content/docs/concepts/material-model.mdx?collection=docs"), "concepts/rendering-pipeline.mdx": () => import("../content/docs/concepts/rendering-pipeline.mdx?collection=docs"), "api/constants.mdx": () => import("../content/docs/api/constants.mdx?collection=docs"), "api/errors.mdx": () => import("../content/docs/api/errors.mdx?collection=docs"), "api/operations.mdx": () => import("../content/docs/api/operations.mdx?collection=docs"), "api/options.mdx": () => import("../content/docs/api/options.mdx?collection=docs"), "api/results.mdx": () => import("../content/docs/api/results.mdx?collection=docs"), "getting-started/installation.mdx": () => import("../content/docs/getting-started/installation.mdx?collection=docs"), "getting-started/quick-start.mdx": () => import("../content/docs/getting-started/quick-start.mdx?collection=docs"), "getting-started/render-a-view-sheet.mdx": () => import("../content/docs/getting-started/render-a-view-sheet.mdx?collection=docs"), "guides/annotate-renders.mdx": () => import("../content/docs/guides/annotate-renders.mdx?collection=docs"), "guides/choose-format-and-quality.mdx": () => import("../content/docs/guides/choose-format-and-quality.mdx?collection=docs"), "guides/frame-the-model.mdx": () => import("../content/docs/guides/frame-the-model.mdx?collection=docs"), "guides/handle-render-failures.mdx": () => import("../content/docs/guides/handle-render-failures.mdx?collection=docs"), "guides/light-the-subject.mdx": () => import("../content/docs/guides/light-the-subject.mdx?collection=docs"), "guides/render-in-the-browser.mdx": () => import("../content/docs/guides/render-in-the-browser.mdx?collection=docs"), "guides/render-multiple-views.mdx": () => import("../content/docs/guides/render-multiple-views.mdx?collection=docs"), }),
};
export default browserCollections;